project_id = "ekahzylmgbngjngkirhl"

[functions.truelayer-auth]
verify_jwt = false

[functions.truelayer-sync]
verify_jwt = false

[functions.extract-nutrition]
verify_jwt = false

[functions.extract-payslip]
verify_jwt = false
